server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: crm
          uri: http://localhost:8081
          predicates:
            - Path=/crm/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1
            - TokenRelay=
            - AddUserHeaderFilter=
            - RemoveRequestHeader=cookie
            - RemoveRequestHeader=authorization
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: тут id
            client-secret: тут секрет
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: login
